### PR TITLE
Support passing zlibOptions and brotliOptions

### PR DESCRIPTION
**Pull request by SystemDisc**
https://github.com/fastify/fastify-compress/issues/106

This does not include tests or a benchmark - just wanted to quickly throw together a first-step in the direction of completing this issue: https://github.com/fastify/fastify-compress/issues/106

This also does not include documentation, simple example is as follows:

```
  server.register(fastifyCompress, {
    brotliOptions: {
      params: {
        [zlib.constants.BROTLI_PARAM_MODE]: zlib.constants.BROTLI_MODE_TEXT, // useful for APIs that primarily return text
        [zlib.constants.BROTLI_PARAM_QUALITY]: 4, // default is 11, max is 11, min is 0
      },
    },
    zlibOptions: {
      level: 9, // default is 9, max is 9, min is 0
    }
  });
```

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
This is great, thanks! Can you add the tests and docs?

**Comment by SystemDisc** [comment]
I will try to when I have time! I just wanted to get it started, so at least there's something to go off of in case someone else has more time. I'm currently working upwards of 90 hours per week. I just happen to be using this library, and saw [the PR](https://github.com/fastify/fastify-compress/issues/106) when I ran into a weird issue with Brotli compression. I disabled Brotli in the project I'm working on because it's not necessary. I wish I had more time to contribute. I love the open-source community. Great stuff!

**Comment by mcollina** [comment]
Ouch, I'm sorry for your 90 hours. Thanks for the contribution!

**Comment by chasingSublimity** [comment]
hi there! I can take a swing at adding docs and tests, if that's alright.

**Comment by Eomm** [comment]
@chasingSublimity go for it! 👍

**Comment by chasingSublimity** [comment]
Ok, here's a first pass. I'm new to Fastify, TypeScript, and zlib so happy to make any improvements you all suggest.

**Comment by SystemDisc** [comment]
Does someone want to run benchmarks, just in case?

**Comment by mcollina** [comment]
Not needed here, thanks for checking!

**Pull request merged**
