### PR TITLE
fix: default brotliOptions does not applied to createBrotliCompress and createBrotliDecompress

### PR DESCRIPTION
**Pull request by stanleyxu2005**
## The problem
I encounted a remarkable performance slow down after migrating from Koa. 
Although the doc mentions [fastify/compress](https://github.com/fastify/fastify-compress/blob/master/README.md?plain=1#L172) already sets the compression level to 4, but it takes too long to compress (3MB for 5 sec) a json. I guess it is configured unexpectedly by default. 

After some investigation, it could be related to the previous merge request #278. 
Unless I explicitly set the compression level to `4`, I will get `11` (BROTLI_DEFAULT_QUALITY). 

## The root cause
The compression level is a member of `brotliOptions.params` not `brotliOptions`. https://nodejs.org/api/zlib.html#class-brotlioptions

And unfortunately the global default option is overwritten by custom option afterwards https://github.com/fastify/fastify-compress/blob/master/index.js#L129

## The change
1. Proposed a fix with additional test cases included. 
2. Added a new test case to ensure with default options, response will be compressed with level `4`. 
3. Changed the existing test case to speicfy the compression level to `8` and check if it is compressed expectedly.

Loop in author of previous commit @kahlstrm as well.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by gurgunday — APPROVED** [review]
lgtm

**Comment by gurgunday** [comment]
There is a type error... can you take a look?

**Comment by stanleyxu2005** [comment]
> There is a type error... can you take a look?
I tried to understand the error, but have no clue why it is failed. 
It expects to throw an type error for `inject()`. I dont see the callback is reachable. Strangely, I checkout the master branch it shows the same error, but the pipeline for previous commits on GitHub are successful.

**Comment by stanleyxu2005** [comment]
After some more code reading, I made a follow-up change. The compress level will be set to 4 for the global option only. If route has its own compression options, it will be merged with global options anway. No need to double overwrite.

**Review by mcollina — APPROVED** [review]
Lgtm. but for some reasons our types tests are failing.

(This can’t land otherwise, and it seems not independent).

**Comment by gurgunday** [comment]
Can you try this?

```js
appWithoutGlobal.inject(
  {
    method: 'GET',
    path: '/throw-a-ts-arg-error',
    headers: {
      'accept-encoding': 'gzip'
    }
  },
  (err) => {
    expectType<Error | undefined>(err) // add undefined
  }
)
```

**Comment by stanleyxu2005** [comment]
@gurgunday @mcollina by changing `expectType<Error>(err)` to `expectType<Error | undefined>(err)`, all test errors are gone at my local env. Committed a new change, and hope all checks will be passed soon. :D

**Comment by gurgunday** [comment]
Yeah seems like ts behavior changed

I will release a new version of this package

**Comment by stanleyxu2005** [comment]
> Yeah seems like ts behavior changed
> 
> I will release a new version of this package

Indeed. It's an interesting test error. 

Thank you both for reviewing the code change. 

This project is quite well coded and documented. I'm glad that I contributed some bugfix for it.👍

**Review by gurgunday — APPROVED** [review]
lgtm

**Pull request merged**
