### PR TITLE
Updated with preferredEncodings option

### PR DESCRIPTION
**Pull request by TJKoury**
Added an option for preferredEncodings, with order.  Will add tests / docs if this pull request is viable.

#61

### CODE REVIEW

**Comment by mcollina** [comment]
I'm sorry we missed this PR!

If you are still interested in contributing, would you mind:

1. restoring the previous linting
2. make the current unit test pass
3. add a unit test for this feature

Thanks!

**Comment by prabirshrestha** [comment]
@TJKoury any updates on this?

**Comment by tigt** [comment]
@mcollina: If this PR is still amenable with `fastify-compress`’s current code, I’d like to take it the rest of the way through validation. The original code hasn’t bit-rotted too much, has it?

**Comment by Eomm** [comment]
Personally I think that is much easier to start from master for this feature getting the if condition that implement it

**Pull request closed without merging**
