### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by cemremengu**
Add win build, remove node 9

### CODE REVIEW

**Comment by cemremengu** [comment]
@mcollina are we still landing this after azure pipelines?

**Comment by mcollina** [comment]
If it passes I'm good in landing.

**Comment by cemremengu** [comment]
I don't have permissions for this one 👀

**Comment by mcollina** [comment]
@cemremengu now you have.

**Comment by cemremengu** [comment]
@mcollina I don't think so, no change happened

**Comment by mcollina** [comment]
try again, my bad

**Comment by cemremengu** [comment]
grazie 👍

**Pull request merged**
