### PR TITLE
test: achieve 100% code coverage

### LINKED ISSUE #112: 100% code coverage
As titled, this repo would benefit from having 100% code coverage (`-100` flag in tap).

### PR DESCRIPTION
**Pull request by darkgl0w**
Hello,

- reaching 100% code coverage (fix https://github.com/fastify/fastify-compress/issues/112)
- remove superfluous and dead code
- add `adm-zip` as a new dev-dep in order to test a specific use case
- remove the check preventing multiple `onSend` hook triggers as it was fixed in `fastify` upstream (possible regressions are monitored by a test case)

~~This PR needs a little bit of work to be completed but early reviews are welcome ^^~~
EDIT: it is now ready to be reviewed

**Note :** Tests and files should be reorganized and structured but I will do this in a new PR (reviewing will be a pain otherwise).
To be done :
- Reorganize test files (renaming following `xxx.test.js` convention)
- Reorganize tests (making groups with sub-tests)
- Maybe going full `async`/`await` syntax test path
- Improve typescript types and tests (should investigate a bit more about what can be done)
- Improve the documentation

main branch :
```
  🌈 SUMMARY RESULTS 🌈  

Suites:   ​4 passed​, ​4 of 4 completed​
Asserts:  ​​​341 passed​, ​of 341​
​Time:​   ​9s​
----------|---------|----------|---------|---------|---------------------------------------------------------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                                                   
----------|---------|----------|---------|---------|---------------------------------------------------------------------
All files |   92.01 |    83.41 |   89.18 |    93.2 |                                                                     
 index.js |   92.01 |    83.41 |   89.18 |    93.2 | 127,129,137,169,189,197,199,215,217,282,284,371-374,484-485,510-511 
----------|---------|----------|---------|---------|---------------------------------------------------------------------
```

after :
```
  🌈 SUMMARY RESULTS 🌈
​
Suites:   ​4 passed​, ​4 of 4 completed​
Asserts:  444 passed​, ​of 444​
​Time:​   ​10s​
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
----------|---------|----------|---------|---------|-------------------
All files |     100 |      100 |     100 |     100 |                   
 index.js |     100 |      100 |     100 |     100 |
----------|---------|----------|---------|---------|-------------------
```

#### Checklist

- [x] run `npm run test`
- [x] tests are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — COMMENTED** [review]
good work!

**Comment by darkgl0w** [comment]
The PR is ready for a reviews.

**Comment by mcollina** [comment]
Thanks, this is amazing!

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
